test

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,3 +1,5 @@
+name: chocolatine
+
 on:
   push:
     branches-ignore:
@@ -6,9 +8,10 @@ on:
     branches-ignore:
      - 'ga-ignore-**'
 
+
 env:
-  MIRROR_URL: "https://github.com/Philou699/BSQ-biggest-square"
-  EXECUTABLES: "bin1,bin2"
+  MIRROR_URL: "https://github.com/Philou699/BSQ-biggest-square/actions"
+  EXECUTABLES: "bsq"
 
 jobs:
   check_repository_cleanliness:
@@ -20,7 +23,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
-          fetch-depth: 0name: chocolatine
+          fetch-depth: 0
 
       - name: Find temp files in all directories
         run: |
@@ -37,52 +40,56 @@ jobs:
       - name: Fail if needed
         if: env.FAIL_TASK == 'true'
         run: exit 1
+ 
+  check_program_compilation:
+    name: Checks if the program compiles correctly and executables files got created
+    runs-on: ubuntu-latest
+    needs: [check_repository_cleanliness]
+    container: epitechcontent/epitest-docker:latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-check_program_compilation:
-  name: Checks if the program compiles correctly and executables files got created
-  runs-on: ubuntu-latest
-  needs: [check_repository_cleanliness]
-  container: epitechcontent/epitest-docker:latest
-  steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-    - run: make
-      timeout-minutes: 2
-    - run: make clean
-    - name: Verifies that files are present and executable
-      run: |
-        echo "FAIL_TASK=false" >> "$GITHUB_ENV"
-        SEARCH_BINARIES="${{ env.EXECUTABLES }}"
-        IFS=$','
-        for BIN in $SEARCH_BINARIES; do
-            if [ ! -f "${BIN}" ]; then
-                echo "::error file=${BIN},title=Binary not found::${BIN}"
-                echo "FAIL_TASK=true" >> "$GITHUB_ENV"
-            fi
-            if [ ! -x "${BIN}" ]; then
-                echo "::error file=${BIN},title=Binary not executable::${BIN}"
-                echo "FAIL_TASK=true" >> "$GITHUB_ENV"
-            fi
-        done
-    - name: Fail if needed
-      if: env.FAIL_TASK == 'true'
-      run: exit 1
+      - run: make
+        timeout-minutes: 2
 
-run_tests:
-  name: Run the program tests (using rule make tests_run)
-  runs-on: ubuntu-latest
-  needs: [check_program_compilation]
-  container: epitechcontent/epitest-docker:latest
-  steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-    - name: Starts tests
-      run: make tests_run
-      timeout-minutes: 2
+      - run: make clean
+
+      - name: Verifies that files are present and executable
+        run: |
+          echo "FAIL_TASK=false" >> "$GITHUB_ENV"
+          SEARCH_BINARIES="${{ env.EXECUTABLES }}"
+          IFS=$','
+          for BIN in $SEARCH_BINARIES; do
+              if [ ! -f "${BIN}" ]; then
+                  echo "::error file=${BIN},title=Binary not found::${BIN}"
+                  echo "FAIL_TASK=true" >> "$GITHUB_ENV"
+              fi
+              if [ ! -x "${BIN}" ]; then
+                  echo "::error file=${BIN},title=Binary not executable::${BIN}"
+                  echo "FAIL_TASK=true" >> "$GITHUB_ENV"
+              fi
+          done
+      - name: Fail if needed
+        if: env.FAIL_TASK == 'true'
+        run: exit 1
+  
+  run_tests:
+    name: Run the program tests (using rule make tests_run)
+    runs-on: ubuntu-latest
+    needs: [check_program_compilation]
+    container: epitechcontent/epitest-docker:latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Starts tests
+        run: make tests_run
+        timeout-minutes: 2
 
   push_to_mirror:
     name: Pushes the current repository files to a given mirror repository
